### PR TITLE
blockchain: don't rely on BlockHeightByHash for prune height calculations

### LINKED ISSUE #2121: btcd v0.24 stuck on block 830326: Failed to process block ..be24f56e: assertion failed: view missing input ..20f56e2f:1
My btcd v0.24 node connected to my https://fork.observer instance seems to be stuck on block 830326. It knows about the chain tip and considers it a valid fork, but fails to process block 000000000000000000022b7ad737a424e1d98f9e4af52ed59a699603ff0a96b0 (830327).

relevant logs:
```
2024-02-13 20:23:34.478 [INF] SYNC: Processed 1 block in the last 15m51.54s (2413 transactions, height 830326, 2024-02-13 20:24:09 +0000 UTC, ~98 MiB cache)
[..]
2024-02-13 20:25:56.414 [ERR] SYNC: Failed to process block 000000000000000000008238554fd52cffc567328e8d87a20ac26a611db9b523: block 0000000000000000000357088139cba6dc295875d7d3b2dd1fd764705727e451 is not in the main chain
[..]
2024-02-13 20:27:09.470 [INF] CHAN: REORGANIZE: Block 00000000000000000001a22c1c720af27eb193d3bc95371df04404eabe24f56e is causing a reorganize.
2024-02-13 20:27:09.471 [INF] CHAN: Flushing UTXO cache of 98 MiB with 13370 entries to disk. For large sizes, this can take up to several minutes...
2024-02-13 20:27:09.832 [ERR] SYNC: Failed to process block 00000000000000000001a22c1c720af27eb193d3bc95371df04404eabe24f56e: assertion failed: view missing input 4538124686f31fdef2930639c5957e72af5796a078127548b58b783420f56e2f:1
```

from fork-observer:
image

Based on `assertion failed: view missing input 4538124686f31fdef2930639c5957e72af5796a078127548b58b783420f56e2f:1`, it seems like https://mempool.space/tx/305b9a9c63df1206dbd409189f0a66e5b01f5f5cb2984b633d574fff33e086d2 can't be applied as https://mempool.space/tx/4538124686f31fdef2930639c5957e72af5796a078127548b58b783420f56e2f#flow=&vout=1 wasn't added to the UTXO set. 

Restarting btcd doesn't seem to fix this problem. I'm not sure yet if this is a local UTXO set inconsistency or a more widespread problem. I haven't seen anyone else having this problem. 

edit: asked on twitter if anyone else is seeing this https://twitter.com/0xB10C/status/1757875766635757689

### PR DESCRIPTION
**Pull request by kcalvinalvin**
Since BlockHeightByHash only returns the heights for blocks that are in the main chain, when a block that is stale gets pruned, this will cause an error in the block height lookup and cause an error in block processing.

Look up the node directly from the index and if the node isn't found, just skip that node. For utxoCache.lastFlushHash, if that isn't found, just force a flush.

Fixes #2121

### CODE REVIEW

**Comment by 0xB10C** [comment]
How can I help test this? Restarting with this patch?

**Comment by kcalvinalvin** [comment]
> How can I help test this? Restarting with this patch?

I don't think we have reconsiderblock here (should push it from utreexod) so you'd have to restart syncing from scratch unfortunately

**Review by Roasbeef — CHANGES_REQUESTED** [review]
Can we re-create the scenarios we've see in the wlid via the full block tests?https://github.com/btcsuite/btcd/blob/13152b35e191385a874294a9dbc902e48b1d71b0/blockchain/fullblocktests/generate.go#L783-L790

https://github.com/btcsuite/btcd/blob/13152b35e191385a874294a9dbc902e48b1d71b0/blockchain/fullblocks_test.go#L132-L134

**Comment by kcalvinalvin** [comment]
> Can we re-create the scenarios we've see in the wlid via the full block tests?
> 
> https://github.com/btcsuite/btcd/blob/13152b35e191385a874294a9dbc902e48b1d71b0/blockchain/fullblocktests/generate.go#L783-L790
> 
> https://github.com/btcsuite/btcd/blob/13152b35e191385a874294a9dbc902e48b1d71b0/blockchain/fullblocks_test.go#L132-L134

I've modified the existing `TestFlushOnPrune` to test for the case where stale blocks are being pruned.
Since pruning only triggers when there's at least 1.5gb of blocks, it's kinda difficult to trigger it on the full block tests so I think it's a better idea to add this test on `TestFlushOnPrune` as that already modifies the block file size by running the test with `ffldb.TstRunWithMaxBlockFileSize()`

**Comment by kcalvinalvin** [comment]
Here's my logs for running `v0.24.0` with and without pruning enabled. Full logs attached.
[btcd-fail.log](https://github.com/btcsuite/btcd/files/14307755/btcd-fail.log)


Without pruning:
```
2024-02-16 14:49:40.291 [INF] BTCD: Version 0.24.0-beta
2024-02-16 14:49:40.291 [INF] BTCD: Loading block database from '/home/calvin/.btcd/data/mainnet/blocks_ffldb'
2024-02-16 14:49:42.176 [INF] BTCD: Block database loaded
2024-02-16 14:49:42.188 [INF] INDX: Committed filter index is enabled
2024-02-16 14:49:42.188 [INF] CHAN: Pre-alloacting for 251 MiB: 
2024-02-16 14:49:42.196 [INF] CHAN: Loading block index...2024-02-16 14:49:44.246 [INF] CHAN: Chain state (height 830395, hash 00000000000000000002e3b19bd2cf690c70d6029f33a6a0a1b8cda5d9cd323a, totaltx 965476556, work 32878101565669194811673855648)
2024-02-16 14:49:46.157 [WRN] RPCS: Can't listen on 127.0.0.1:8334: listen tcp4 127.0.0.1:8334: bind: address already in use
2024-02-16 14:49:46.157 [INF] RPCS: RPC server listening on [::1]:8334
2024-02-16 14:49:46.301 [INF] AMGR: Loaded 47715 addresses from file '/home/calvin/.btcd/data/mainnet/peers.json'
2024-02-16 14:49:46.301 [INF] CMGR: Server listening on 0.0.0.0:8333
2024-02-16 14:49:46.301 [INF] CMGR: Server listening on [::]:8333
2024-02-16 14:49:46.314 [INF] CMGR: 39 addresses found from DNS seed seed.bitcoin.sipa.be
2024-02-16 14:49:46.537 [INF] CMGR: 37 addresses found from DNS seed seed.btc.petertodd.net
2024-02-16 14:49:46.662 [INF] SYNC: New valid peer 174.20.57.30:8333 (outbound) (/Satoshi:25.0.0/)
2024-02-16 14:49:46.662 [INF] SYNC: Syncing to block height 830683 from peer 174.20.57.30:8333
2024-02-16 14:49:46.720 [INF] SYNC: New valid peer 167.88.11.203:8333 (outbound) (/Satoshi:22.0.0/)
2024-02-16 14:49:46.848 [INF] CMGR: 40 addresses found from DNS seed seed.bitnodes.io
2024-02-16 14:49:46.927 [INF] CMGR: 26 addresses found from DNS seed seed.bitcoinstats.com
2024-02-16 14:49:47.100 [INF] CMGR: 31 addresses found from DNS seed dnsseed.bluematt.me
2024-02-16 14:49:47.253 [INF] CMGR: 36 addresses found from DNS seed dnsseed.bitcoin.dashjr.org
2024-02-16 14:49:47.380 [INF] SYNC: New valid peer 37.143.118.174:8333 (outbound) (/Satoshi:26.0.0/)
2024-02-16 14:49:47.405 [INF] SYNC: New valid peer 156.146.137.142:8333 (outbound) (/Satoshi:26.0.0/)
2024-02-16 14:49:47.918 [INF] SYNC: Lost peer 37.143.118.174:8333 (outbound)
2024-02-16 14:49:48.284 [INF] CMGR: 37 addresses found from DNS seed seed.bitcoin.jonasschnelli.ch
2024-02-16 14:49:48.358 [INF] SYNC: New valid peer 66.135.24.251:8333 (outbound) (/Satoshi:22.0.0/)
2024-02-16 14:49:55.098 [INF] CHAN: Flushing UTXO cache of 98 MiB with 11959 entries to disk. For large sizes, this can take up to several minutes...
2024-02-16 14:50:00.324 [INF] SYNC: Processed 2 blocks in the last 14.17s (5595 transactions, height 830397, 2024-02-14 18:12:32 +0900 KST, ~98 MiB cache)
2024-02-16 14:50:14.698 [INF] SYNC: Processed 2 blocks in the last 14.37s (3841 transactions, height 830399, 2024-02-14 18:22:37 +0900 KST, ~99 MiB cache)
2024-02-16 14:50:16.651 [INF] SYNC: New valid peer 104.13.168.146:8333 (outbound) (/Satoshi:24.0.1/)
2024-02-16 14:50:16.844 [INF] SYNC: New valid peer 212.51.136.50:8333 (outbound) (/Satoshi:24.0.1/)
2024-02-16 14:50:16.891 [INF] SYNC: New valid peer 85.214.192.204:8333 (outbound) (/Satoshi:26.0.0/)
2024-02-16 14:50:17.523 [INF] SYNC: Lost peer 85.214.192.204:8333 (outbound)
2024-02-16 14:50:17.811 [INF] SYNC: New valid peer 142.171.179.169:8333 (outbound) (/Satoshi:25.0.0/)
2024-02-16 14:50:25.692 [INF] SYNC: Processed 2 blocks in the last 10.99s (5763 transactions, height 830401, 2024-02-14 19:08:10 +0900 KST, ~101 MiB cache)
2024-02-16 14:50:37.760 [INF] SYNC: Processed 2 blocks in the last 12.06s (5254 transactions, height 830403, 2024-02-14 19:25:37 +0900 KST, ~102 MiB cache)
2024-02-16 14:50:46.912 [INF] SYNC: New valid peer 65.108.103.225:8333 (outbound) (/Satoshi:24.0.1/)
2024-02-16 14:50:47.719 [INF] SYNC: Lost peer 65.108.103.225:8333 (outbound)
2024-02-16 14:50:48.138 [INF] SYNC: New valid peer 99.29.112.187:8333 (outbound) (/Satoshi:0.20.1/)
2024-02-16 14:50:48.254 [INF] SYNC: Lost peer 99.29.112.187:8333 (outbound)
2024-02-16 14:50:48.695 [INF] SYNC: New valid peer 188.92.20.9:8333 (outbound) (/Satoshi:26.0.0/)
2024-02-16 14:50:49.508 [INF] SYNC: Processed 2 blocks in the last 11.74s (4683 transactions, height 830405, 2024-02-14 19:44:42 +0900 KST, ~103 MiB cache)
2024-02-16 14:50:50.492 [INF] SYNC: Lost peer 188.92.20.9:8333 (outbound)
2024-02-16 14:51:01.903 [INF] SYNC: Processed 2 blocks in the last 12.39s (4020 transactions, height 830407, 2024-02-14 19:54:05 +0900 KST, ~104 MiB cache)
2024-02-16 14:51:13.308 [INF] SYNC: Processed 2 blocks in the last 11.4s (5294 transactions, height 830409, 2024-02-14 20:20:38 +0900 KST, ~105 MiB cache)
2024-02-16 14:51:20.789 [INF] SYNC: New valid peer 70.181.225.218:8333 (outbound) (/Satoshi:26.0.0/)
2024-02-16 14:51:24.449 [INF] SYNC: Processed 2 blocks in the last 11.14s (5030 transactions, height 830411, 2024-02-14 20:49:50 +0900 KST, ~106 MiB cache)
2024-02-16 14:51:39.113 [INF] SYNC: Processed 2 blocks in the last 14.66s (2794 transactions, height 830413, 2024-02-14 20:51:09 +0900 KST, ~107 MiB cache)
2024-02-16 14:51:50.162 [INF] SYNC: Processed 2 blocks in the last 11.04s (4504 transactions, height 830415, 2024-02-14 21:11:52 +0900 KST, ~108 MiB cache)
2024-02-16 14:52:03.930 [INF] SYNC: Processed 2 blocks in the last 13.76s (2178 transactions, height 830417, 2024-02-14 21:15:41 +0900 KST, ~109 MiB cache)
2024-02-16 14:52:15.292 [INF] SYNC: Processed 2 blocks in the last 11.36s (5226 transactions, height 830419, 2024-02-14 21:58:03 +0900 KST, ~110 MiB cache)
2024-02-16 14:52:26.696 [INF] SYNC: Processed 2 blocks in the last 11.4s (4197 transactions, height 830421, 2024-02-14 22:15:23 +0900 KST, ~112 MiB cache)
2024-02-16 14:52:38.175 [INF] SYNC: Processed 2 blocks in the last 11.47s (4129 transactions, height 830423, 2024-02-14 22:20:58 +0900 KST, ~112 MiB cache)
2024-02-16 14:52:50.314 [INF] SYNC: Processed 2 blocks in the last 12.13s (2931 transactions, height 830425, 2024-02-14 22:27:36 +0900 KST, ~113 MiB cache)
2024-02-16 14:53:02.620 [INF] SYNC: Processed 2 blocks in the last 12.3s (4112 transactions, height 830427, 2024-02-14 22:43:15 +0900 KST, ~114 MiB cache)
2024-02-16 14:53:13.954 [INF] SYNC: Processed 2 blocks in the last 11.33s (5242 transactions, height 830429, 2024-02-14 23:10:10 +0900 KST, ~116 MiB cache)
2024-02-16 14:53:24.697 [INF] SYNC: Processed 2 blocks in the last 10.74s (5355 transactions, height 830431, 2024-02-14 23:38:04 +0900 KST, ~117 MiB cache)
2024-02-16 14:53:37.020 [INF] SYNC: Processed 2 blocks in the last 12.32s (3800 transactions, height 830433, 2024-02-14 23:50:48 +0900 KST, ~117 MiB cache)
2024-02-16 14:53:48.762 [INF] SYNC: Processed 2 blocks in the last 11.74s (5136 transactions, height 830435, 2024-02-15 00:07:13 +0900 KST, ~118 MiB cache)
2024-02-16 14:54:00.929 [INF] SYNC: Processed 2 blocks in the last 12.16s (4730 transactions, height 830437, 2024-02-15 00:22:32 +0900 KST, ~119 MiB cache)
2024-02-16 14:54:12.650 [INF] SYNC: Processed 2 blocks in the last 11.72s (5053 transactions, height 830439, 2024-02-15 00:33:22 +0900 KST, ~120 MiB cache)
2024-02-16 14:54:26.590 [INF] SYNC: Processed 3 blocks in the last 13.94s (7346 transactions, height 830442, 2024-02-15 01:47:59 +0900 KST, ~123 MiB cache)
2024-02-16 14:54:39.996 [INF] SYNC: Processed 3 blocks in the last 13.4s (7650 transactions, height 830445, 2024-02-15 02:06:03 +0900 KST, ~125 MiB cache)
2024-02-16 14:54:55.280 [INF] SYNC: Processed 3 blocks in the last 15.28s (5296 transactions, height 830448, 2024-02-15 02:08:29 +0900 KST, ~127 MiB cache)
2024-02-16 14:54:55.280 [INF] CHAN: Flushing UTXO cache of 127 MiB with 487487 entries to disk. For large sizes, this can take up to several minutes...
2024-02-16 14:55:07.136 [INF] SYNC: Processed 2 blocks in the last 11.85s (790 transactions, height 830450, 2024-02-15 02:09:15 +0900 KST, ~99 MiB cache)
2024-02-16 14:55:21.819 [INF] SYNC: Processed 3 blocks in the last 14.68s (7781 transactions, height 830453, 2024-02-15 02:21:51 +0900 KST, ~101 MiB cache)
2024-02-16 14:55:32.291 [INF] SYNC: Processed 2 blocks in the last 10.47s (5190 transactions, height 830455, 2024-02-15 02:43:22 +0900 KST, ~103 MiB cache)
2024-02-16 14:55:47.478 [INF] SYNC: Processed 3 blocks in the last 15.18s (8483 transactions, height 830458, 2024-02-15 03:01:44 +0900 KST, ~105 MiB cache)
2024-02-16 14:55:59.150 [INF] SYNC: Processed 2 blocks in the last 11.67s (3887 transactions, height 830460, 2024-02-15 03:14:05 +0900 KST, ~106 MiB cache)
2024-02-16 14:56:12.014 [INF] SYNC: Processed 2 blocks in the last 12.86s (2700 transactions, height 830462, 2024-02-15 03:17:18 +0900 KST, ~108 MiB cache)
2024-02-16 14:56:24.909 [INF] SYNC: Processed 3 blocks in the last 12.89s (10012 transactions, height 830465, 2024-02-15 04:33:09 +0900 KST, ~110 MiB cache)
2024-02-16 14:56:37.651 [INF] SYNC: Processed 3 blocks in the last 12.74s (8689 transactions, height 830468, 2024-02-15 05:08:01 +0900 KST, ~113 MiB cache)
2024-02-16 14:56:51.663 [INF] SYNC: Processed 3 blocks in the last 14.01s (7422 transactions, height 830471, 2024-02-15 05:19:50 +0900 KST, ~114 MiB cache)
2024-02-16 14:57:06.285 [INF] SYNC: Processed 3 blocks in the last 14.62s (8261 transactions, height 830474, 2024-02-15 06:07:18 +0900 KST, ~116 MiB cache)
2024-02-16 14:57:19.093 [INF] SYNC: Processed 2 blocks in the last 12.8s (3602 transactions, height 830476, 2024-02-15 06:11:31 +0900 KST, ~117 MiB cache)
2024-02-16 14:57:32.509 [INF] SYNC: Processed 3 blocks in the last 13.41s (9049 transactions, height 830479, 2024-02-15 07:21:39 +0900 KST, ~119 MiB cache)
2024-02-16 14:57:43.629 [INF] SYNC: Processed 2 blocks in the last 11.11s (5282 transactions, height 830481, 2024-02-15 07:44:52 +0900 KST, ~120 MiB cache)
2024-02-16 14:57:54.909 [INF] SYNC: Processed 2 blocks in the last 11.27s (4087 transactions, height 830483, 2024-02-15 08:09:10 +0900 KST, ~121 MiB cache)
2024-02-16 14:58:06.079 [INF] SYNC: Processed 2 blocks in the last 11.17s (5105 transactions, height 830485, 2024-02-15 08:39:49 +0900 KST, ~122 MiB cache)
2024-02-16 14:58:18.140 [INF] SYNC: Processed 2 blocks in the last 12.06s (4001 transactions, height 830487, 2024-02-15 09:03:14 +0900 KST, ~123 MiB cache)
2024-02-16 14:58:31.897 [INF] SYNC: Processed 2 blocks in the last 13.75s (3361 transactions, height 830489, 2024-02-15 09:16:51 +0900 KST, ~123 MiB cache)
2024-02-16 14:58:46.597 [INF] SYNC: Processed 2 blocks in the last 14.69s (1515 transactions, height 830491, 2024-02-15 09:20:06 +0900 KST, ~124 MiB cache)
```

With pruning:
```
2024-02-16 16:20:42.635 [INF] BTCD: Version 0.24.0-beta
2024-02-16 16:20:42.635 [INF] BTCD: Loading block database from '/home/calvin/.btcd/data/mainnet/blocks_ffldb'
2024-02-16 16:20:43.087 [INF] BTCD: Block database loaded
2024-02-16 16:20:43.098 [INF] INDX: Committed filter index is enabled
2024-02-16 16:20:43.098 [INF] CHAN: Pre-alloacting for 251 MiB: 
2024-02-16 16:20:43.102 [INF] CHAN: Loading block index...
2024-02-16 16:20:45.186 [INF] CHAN: Chain state (height 830687, hash 0000000000000000000037d512b01992e7b0109ff269e13edd5b3950f8c6bf6e, totaltx 966077512, work 32975358517829526424473523104)
2024-02-16 16:20:46.963 [WRN] RPCS: Can't listen on 127.0.0.1:8334: listen tcp4 127.0.0.1:8334: bind: address already in use
2024-02-16 16:20:46.963 [INF] RPCS: RPC server listening on [::1]:8334
2024-02-16 16:20:47.106 [INF] AMGR: Loaded 47768 addresses from file '/home/calvin/.btcd/data/mainnet/peers.json'
2024-02-16 16:20:47.110 [INF] CMGR: Server listening on 0.0.0.0:8333
2024-02-16 16:20:47.110 [INF] CMGR: Server listening on [::]:8333
2024-02-16 16:20:47.363 [INF] SYNC: New valid peer 65.0.3.156:8333 (outbound) (/Satoshi:0.21.1/)
2024-02-16 16:20:47.363 [INF] SYNC: Syncing to block height 830687 from peer 65.0.3.156:8333
2024-02-16 16:20:47.493 [INF] SYNC: New valid peer 66.58.243.215:8333 (outbound) (/Satoshi:23.0.0/)
2024-02-16 16:20:47.521 [INF] SYNC: New valid peer 165.22.229.88:8333 (outbound) (/Satoshi:0.20.1/)
2024-02-16 16:20:47.560 [INF] CMGR: 37 addresses found from DNS seed seed.btc.petertodd.net
2024-02-16 16:20:47.615 [INF] SYNC: Lost peer 66.58.243.215:8333 (outbound)
2024-02-16 16:20:47.663 [INF] SYNC: New valid peer 188.68.53.44:8333 (outbound) (/Satoshi:22.0.0/)
2024-02-16 16:20:47.720 [INF] CMGR: 26 addresses found from DNS seed seed.bitcoinstats.com
2024-02-16 16:20:47.734 [INF] SYNC: New valid peer 82.66.53.98:8333 (outbound) (/Satoshi:26.0.0/)
2024-02-16 16:20:47.785 [INF] CMGR: 40 addresses found from DNS seed seed.bitnodes.io
2024-02-16 16:20:47.905 [INF] CMGR: 31 addresses found from DNS seed dnsseed.bluematt.me
2024-02-16 16:20:47.967 [INF] SYNC: New valid peer 164.132.200.159:8333 (outbound) (/Satoshi:24.0.1/)
2024-02-16 16:20:48.117 [INF] SYNC: Lost peer 164.132.200.159:8333 (outbound)
2024-02-16 16:20:48.343 [INF] SYNC: New valid peer 193.169.245.118:8333 (outbound) (/Satoshi:24.99.0/)
2024-02-16 16:20:48.492 [INF] CMGR: 37 addresses found from DNS seed seed.bitcoin.jonasschnelli.ch
2024-02-16 16:20:48.662 [INF] SYNC: New valid peer 65.108.122.251:8333 (outbound) (/Satoshi:25.1.0/)
2024-02-16 16:20:48.729 [INF] SYNC: Lost peer 65.108.122.251:8333 (outbound)
2024-02-16 16:20:48.991 [INF] CMGR: 36 addresses found from DNS seed dnsseed.bitcoin.dashjr.org
2024-02-16 16:20:49.674 [INF] SYNC: New valid peer 86.215.168.115:8333 (outbound) (/Satoshi:26.0.0/)
2024-02-16 16:20:51.605 [INF] CMGR: 39 addresses found from DNS seed seed.bitcoin.sipa.be
2024-02-16 16:21:17.364 [INF] SYNC: Lost peer 65.0.3.156:8333 (outbound)
2024-02-16 16:21:17.364 [INF] SYNC: Syncing to block height 830688 from peer 188.68.53.44:8333
2024-02-16 16:21:17.911 [INF] SYNC: New valid peer 159.224.238.145:8333 (outbound) (/Satoshi:24.0.1/)
2024-02-16 16:21:21.123 [ERR] SYNC: Failed to process block 0000000000000000000051a4d8fe6aa337190ab387fb73da51ccdc0c45e20b93: block 000000000000000000032956cbfd8721abe0572d81542e75e38e6185312bee09 is not in the main chain
2024-02-16 16:21:22.706 [INF] BTCD: Received signal (interrupt).  Shutting down...
2024-02-16 16:21:22.706 [INF] BTCD: Gracefully shutting down the server...
2024-02-16 16:21:22.706 [WRN] SRVR: Server shutting down
2024-02-16 16:21:22.706 [WRN] RPCS: RPC server shutting down
2024-02-16 16:21:22.706 [INF] RPCS: RPC server shutdown complete
2024-02-16 16:21:24.734 [INF] SRVR: New peer 88.17.82.14:8333 (outbound) ignored - server is shutting down
2024-02-16 16:21:24.734 [WRN] SYNC: Received done peer message for unknown peer 88.17.82.14:8333 (outbound)
2024-02-16 16:21:36.464 [INF] SYNC: Lost peer 159.224.238.145:8333 (outbound)
```

**Comment by 0xB10C** [comment]
> I don't think we have reconsiderblock here (should push it from utreexod) so you'd have to restart syncing from scratch unfortunately

Alright, done that. I still have a copy of the old datadir in-case anyone needs it for testing or further debugging.

**Comment by kcalvinalvin** [comment]
Added additional comments in the new code

File: blockchain/utxocache.go [hunk 1]
```diff
@@ -725,22 +726,34 @@ func (b *BlockChain) InitConsistentState(tip *blockNode, interrupt <-chan struct
...
 	// Loop through all the block hashes and find out what the highest block height
 	// among the deleted hashes is.
 	highestDeletedHeight := int32(-1)
 	for _, deletedBlockHash := range deletedBlockHashes {
-		height, err := b.BlockHeightByHash(&deletedBlockHash)
-		if err != nil {
-			return false, err
+		node := b.index.LookupNode(&deletedBlockHash)
+		if node == nil {
+			// If we couldn't find this node, just skip it and try the next
```
Comment (halseth) [inline blockchain/utxocache.go:749]: This comment doesn't seem consistent with the commit message, as a stale block might well happen, and this case is not necessarily a db corruption.

File: blockchain/utxocache_test.go [hunk 2]
```diff
@@ -749,36 +749,40 @@ func TestFlushOnPrune(t *testing.T) {
...
-	shouldExist := func(dbTx database.Tx, blockHash *chainhash.Hash) {
+	shouldExist := func(dbTx database.Tx, blockHash *chainhash.Hash) error {
 		bytes, err := dbTx.FetchBlock(blockHash)
 		if err != nil {
-			t.Fatal(err)
+			return err
 		}
 		block, err := btcutil.NewBlockFromBytes(bytes)
 		if err != nil {
-			t.Fatalf("didn't find block %v. %v", blockHash, err)
```
Comment (Roasbeef) [inline blockchain/utxocache_test.go:759]: Ah yeh calling `t.Fatalf` inside a goroutine outside the main test execution goroutine can trigger weird behavior (deadlock, panic, etc).

File: blockchain/utxocache.go [hunk 3]
```diff
@@ -617,6 +617,7 @@ func (b *BlockChain) InitConsistentState(tip *blockNode, interrupt <-chan struct
 
 		// Set the last flush hash as it's the default value of 0s.
 		s.lastFlushHash = tip.hash
+		s.lastFlushTime = time.Now()
```
Comment (Roasbeef) [inline blockchain/utxocache.go:620]: Independent bug fix? 

Or before time would be the zero value of `time.Time` so the subsequent checks work properly as any time is after `timeZero`?

File: blockchain/utxocache.go [hunk 4]
```diff
@@ -725,22 +726,34 @@ func (b *BlockChain) InitConsistentState(tip *blockNode, interrupt <-chan struct
...
+		// flush to be safe and that will set the last flush hash again.
+		//
+		// This realistically should never happen as nodes are never deleted from
+		// the block index.  This happening likely means that there's a hardware
+		// error which is something we can't recover from.  The best that we can
+		// do here is to just force a flush and hope that the newly set
+		// lastFlushHash doesn't error.
+		return true, nil
+	}
+	lastFlushHeight := node.Height()
```
Comment (Roasbeef) [inline blockchain/utxocache.go:741]: Style nit: missing new line above this variable initialization.

File: blockchain/utxocache.go (hunk 1 above)
Comment (Roasbeef) [reply blockchain/utxocache.go:749]: So this is reading from `blockIndex`, which will store a mapping of `hash => height` for every block we've ever seen:
* https://github.com/btcsuite/btcd/blob/9ea2eea99bcb799d43f4164ebae41a61df90d133/blockchain/accept.go#L70-L74
* https://github.com/btcsuite/btcd/blob/9ea2eea99bcb799d43f4164ebae41a61df90d133/blockchain/chainio.go#L1382-L1402


We never delete from this index, so even if it's a stale block, if we attempt to accept it in the past, it _should_ be in this index. 

The issue with this code was that it used `BlockHeightByHash`, which only checks for block currently in the main chain: https://github.com/btcsuite/btcd/blob/9ea2eea99bcb799d43f4164ebae41a61df90d133/blockchain/chain.go#L1519

Before this would error out, and cause the entire daemon to be torn down.

File: blockchain/utxocache.go (hunk 3 above)
Comment (kcalvinalvin) [reply blockchain/utxocache.go:620]: Yeah this is a separate fix. The only thing it affects is the immediate flushing on start when upgrading from a v0.23 node.

I can make it into a separate PR if requested.

File: blockchain/utxocache.go (hunk 1 above)
Comment (kcalvinalvin) [reply blockchain/utxocache.go:749]: Right as roasbeef mentioned, since we never delete entries from the blockIndex, if we have the block on disk, the index should also have it.

Does this clarify the comment?

File: blockchain/utxocache.go (hunk 4 above)
Comment (kcalvinalvin) [reply blockchain/utxocache.go:742]: Addressed in the latest push

**Review by Roasbeef — APPROVED** [review]
LGTM 🥯
