### PR TITLE
rpcclient: add bitcoind version dependent error matching

### LINKED ISSUE #2404: string-matching will break in bitcoind v30.0
"non-mandatory-script-verify-flag" is replaced with "mempool-script-verify-flag-failed"

See: https://github.com/bitcoin/bitcoin/pull/33050/
Should change here: https://github.com/btcsuite/btcd/blob/baebb836c2d4692da3de3b0d437f4da6ce915546/rpcclient/errors.go#L334-L335

### PR DESCRIPTION
**Pull request by guggero**
Fixes #2404.
If different versions of bitcoind return different error strings, we need a way to match those as well.

### CODE REVIEW

**Comment by yyforyongyu** [comment]
@ziggie1984 maybe you could take a look?

File: rpcclient/errors.go [hunk 1]
```diff
@@ -338,6 +338,17 @@ func (r BitcoindRPCErr) Error() string {
...
 
+// BitcoindErrMap is a map of additional errors bitcoind can throw that are
+// version dependent (e.g. versions up to v29 return the error as specified in
+// `Error()` above, while versions v30 and beyond return the error as mapped
+// here.
+var BitcoindErrMap = map[string]error{
+	// The error message was changed in
+	// https://github.com/bitcoin/bitcoin/pull/33050 which will be included
+	// in bitcoind v30.0 and beyond.
+	"mempool script verify flag failed": ErrNonMandatoryScriptVerifyFlag,
```
Comment (ziggie1984) [inline rpcclient/errors.go:350]: can you also add: `block-script-verify-flag-failed` see https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes-33183.md ?

File: rpcclient/errors.go [hunk 2]
```diff
@@ -338,6 +338,17 @@ func (r BitcoindRPCErr) Error() string {
 	return "unknown error"
 }
 
+// BitcoindErrMap is a map of additional errors bitcoind can throw that are
+// version dependent (e.g. versions up to v29 return the error as specified in
+// `Error()` above, while versions v30 and beyond return the error as mapped
+// here.
+var BitcoindErrMap = map[string]error{
```
Comment (ziggie1984) [inline rpcclient/errors.go:346]: Why don't we just introduce 2 new errors instead of mapping it to the old one ?

**Review by ziggie1984 — COMMENTED** [review]
Thank you for monitoring the core lib, wondering if we just define these 2 new errors instead of mapping ?

File: rpcclient/errors.go (hunk 1 above)
Comment (guggero) [reply rpcclient/errors.go:350]: Ah, yes. Added.

File: rpcclient/errors.go (hunk 2 above)
Comment (guggero) [reply rpcclient/errors.go:346]: Because the errors were simply renamed, I wanted to keep the same semantic meaning (e.g. the same error constant) in case we matched on them anywhere. We currently don't, so we could've added new errors. But I still find it slightly better in terms of understanding what's going on. Added some additional context to the comment of the new map, why we use it and when we should create new constants.
I hope that makes sense to you?

**Comment by guggero** [comment]
@Roasbeef requesting merge override.
