### PR TITLE
base58: fix decoding issue

### LINKED ISSUE #1922: DecodeAddress panic when address contains emoji characters.
The function will crash when address contains a emoji characters such as `😁`
`func DecodeAddress(addr string, defaultNet *chaincfg.Params) (Address, error)`

https://github.com/btcsuite/btcd/blob/4350859a7b9f7d744c1ee717e60cd29e466e2a25/btcutil/address.go#L148

### PR DESCRIPTION
**Pull request by guggero**
Fixes #1922.

### CODE REVIEW

File: btcutil/base58/base58_test.go [hunk 1]
```diff
@@ -43,6 +43,8 @@ var invalidStringTests = []struct {
 	{"4kl8", ""},
 	{"0OIl", ""},
 	{"!@#$%^&*()-_=+~`", ""},
+	{"abcd\xd80", ""},
+	{"abcd\U000020BF", ""},
```
Comment (sputn1ck) [inline btcutil/base58/base58_test.go:47]: nice choice

**Review by sputn1ck — APPROVED** [review]
tACK LGTM !

**Review by Roasbeef — APPROVED** [review]
LGTM 💎
