### PR TITLE
btcec: Optimize normalize and NAF, correct normalize, and add tests.

### LINKED ISSUE #709: btcec: recovers certain signature without error
I am trying to use package btcec in go-ethereum for the sake of having a pure-go build.
During testing, I discovered that btcec.RecoverCompact accepts certain signatures which
are rejected by both libsecp256k1 and the ECDSA_SIG_recover_key_GFp function previously
used in bitcoind (before they switched to libsecp256k1).

The signature and message in question are:

``` text
msg = 00c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c
sig = 1c00b1693892219d736caba55bdb67216e485557ea6b6af75f37096c9aa6a5a75f00b940b1d03b21e36b0e47e79769f095fe2ab855bd91e3a38756b7d75a9c4549
```

See https://github.com/fjl/btcec-issue for code that reproduces the issue.
Output from `make test` in that repo (the signature above is sig 2):

``` text
== sig 1 libsecp256k1:
pubkey: 04E32DF42865E97135ACFB65F3BAE71BDC86F4D49150AD6A440B6F15878109880A0A2B2667F7E725CEEA70C673093BF67663E0312623C8E091B13CF2C0F11EF652
== sig 2 libsecp256k1:
recover failed
== sig 1 openssl:
pubkey: 04E32DF42865E97135ACFB65F3BAE71BDC86F4D49150AD6A440B6F15878109880A0A2B2667F7E725CEEA70C673093BF67663E0312623C8E091B13CF2C0F11EF652
== sig 2 openssl:
recover failed
== sig 1 btcec:
pubkey: 04E32DF42865E97135ACFB65F3BAE71BDC86F4D49150AD6A440B6F15878109880A0A2B2667F7E725CEEA70C673093BF67663E0312623C8E091B13CF2C0F11EF652
== sig 2 btcec:
pubkey: 04D808F6C95B99D15DC39CC452D5B1A37633455A3CC0B96B191AA1873A6174B00B4A58079675094B2459AA57E09505BF9A22DD6EB988FBB3A471B1F13D8D74CFF7
```

It might also be that I am using btcec.RecoverCompact incorrectly.

### PR DESCRIPTION
**Pull request by davecgh**
This modifies the normalize function of the internal field value to both optimize it and address an issue where the reduction could lead to an incorrect result with a small range of values along with some tests to ensure the behavior is correct.

It also contains contributions from @jimmysong to optimize NAF to avoid returning the unneeded bit when there is not a carry and adds a bunch of unit tests.

The following benchmark shows the relative speedups as a result of the optimization on my system.  In particular, the changes result in approximately a 14% speedup in Normalize, which ultimately translates to a 2% speedup in signature verifies.

```
benchmark                        old ns/op     new ns/op     delta
--------------------------------------------------------------------
BenchmarkAddJacobian             1364          1289          -5.50%
BenchmarkAddJacobianNotZOne      3150          3091          -1.87%
BenchmarkScalarBaseMult          134117        132816        -0.97%
BenchmarkScalarBaseMultLarge     135067        132966        -1.56%
BenchmarkScalarMult              411218        402217        -2.19%
BenchmarkSigVerify               671585        657833        -2.05%
BenchmarkFieldNormalize          36.0          31.0          -13.89%
```

Fixes #709.

### CODE REVIEW

File: btcec/bench_test.go [hunk 1]
```diff
@@ -111,3 +111,13 @@ func BenchmarkSigVerify(b *testing.B) {
...
 	}
 }
+
+// BenchmarkFieldNormalize benchmarks how long it takes the internal field
+// to perform normalization (which includes modular reduction).
+func BenchmarkFieldNormalize(b *testing.B) {
+	// The normalize function is constant time so default value is fine.
+	f := new(fieldVal)
+	for i := 0; i < b.N; i++ {
+		_ = f.Normalize()
```
Comment (jimmysong) [inline btcec/bench_test.go]: I don't think you need the `_ = `

Comment (davecgh) [inline btcec/bench_test.go]: Correct.  I'll nuke it.
