### PR TITLE
netsync/manager: detect stalled sync peer

### LINKED ISSUE #186: Stopped downloading blocks on initial sync
I was doing the initial sync, and now this happens every time I start btcd. It won't make any progress at all.

```
foo@bar ~/g/bin > ./btcd
07:21:59 2014-11-14 [INF] BTCD: Version 0.9.0-beta
07:21:59 2014-11-14 [INF] BTCD: Loading block database from '/home/adam/.btcd/data/m
07:22:01 2014-11-14 [INF] BTCD: Block database loaded with block height 300652
07:22:01 2014-11-14 [INF] BMGR: Generating initial block node index.  This may take a while...
07:22:41 2014-11-14 [INF] BMGR: Block index generation complete
07:22:41 2014-11-14 [INF] SRVR: Server listening on [::]:8333
07:22:41 2014-11-14 [INF] RPCS: RPC server listening on 127.0.0.1:8334
07:22:41 2014-11-14 [INF] RPCS: RPC server listening on [::1]:8334
07:22:41 2014-11-14 [INF] SRVR: Server listening on 0.0.0.0:8333
07:22:41 2014-11-14 [INF] AMGR: Loaded 8255 addresses from file '/home/adam/.btcd/data/mainnet/peers.json'
07:22:41 2014-11-14 [INF] DISC: 13 addresses found from DNS seed bitseed.xf2.org
07:22:41 2014-11-14 [INF] DISC: 27 addresses found from DNS seed dnsseed.bluematt.me
07:22:41 2014-11-14 [INF] DISC: 27 addresses found from DNS seed seed.bitnodes.io
07:22:41 2014-11-14 [INF] DISC: 26 addresses found from DNS seed seed.bitcoinstats.com
07:22:41 2014-11-14 [INF] DISC: 43 addresses found from DNS seed dnsseed.bitcoin.dashjr.org
07:22:42 2014-11-14 [INF] DISC: 44 addresses found from DNS seed seed.bitcoin.sipa.be
07:22:43 2014-11-14 [INF] DISC: 26 addresses found from DNS seed seeds.bitcoin.open-nodes.org
07:22:52 2014-11-14 [INF] BMGR: New valid peer 173.20.137.87:8333 (outbound) (/Satoshi:0.9.1/)
07:22:52 2014-11-14 [INF] BMGR: Syncing to block height 329973 from peer 173.20.137.87:8333
07:22:52 2014-11-14 [INF] BMGR: Downloading headers for blocks 300653 to 319400 from peer 173.20.137.87:8333
07:22:52 2014-11-14 [WRN] BMGR: Received block header that does notproperly connect to the chain from peer 173.20.137.87:8333 -- disconnecting
07:22:52 2014-11-14 [INF] BMGR: Lost peer 173.20.137.87:8333 (outbound)
07:22:52 2014-11-14 [WRN] BMGR: No sync peer candidates available
07:22:52 2014-11-14 [INF] BMGR: New valid peer 198.255.137.114:8333 (outbound) (/Satoshi:0.9.3/)
07:22:52 2014-11-14 [INF] BMGR: Syncing to block height 329973 from peer 198.255.137.114:8333
07:22:52 2014-11-14 [INF] BMGR: Downloading headers for blocks 300653 to 319400 from peer 198.255.137.114:8333
07:22:52 2014-11-14 [INF] BMGR: New valid peer 187.204.174.154:8333 (outbound) (/Satoshi:0.8.1/)
07:22:53 2014-11-14 [WRN] BMGR: Received block header that does notproperly connect to the chain from peer 198.255.137.114:8333 -- disconnecting
07:22:53 2014-11-14 [INF] BMGR: Lost peer 198.255.137.114:8333 (outbound)
07:22:53 2014-11-14 [INF] BMGR: Syncing to block height 329973 from peer 187.204.174.154:8333
07:22:53 2014-11-14 [INF] BMGR: Downloading headers for blocks 300653 to 319400 from peer 187.204.174.154:8333
07:23:10 2014-11-14 [WRN] BMGR: Received block header that does notproperly connect to the chain from peer 187.204.174.154:8333 -- disconnecting
07:23:10 2014-11-14 [INF] BMGR: Lost peer 187.204.174.154:8333 (outbound)
07:23:10 2014-11-14 [WRN] BMGR: No sync peer candidates available
07:24:59 2014-11-14 [INF] BMGR: New valid peer 198.255.137.114:8333 (outbound) (/Satoshi:0.9.3/)
07:24:59 2014-11-14 [INF] BMGR: Syncing to block height 329973 from peer 198.255.137.114:8333
07:24:59 2014-11-14 [INF] BMGR: Downloading headers for blocks 300653 to 319400 from peer 198.255.137.114:8333
07:24:59 2014-11-14 [INF] BMGR: New valid peer 24.154.138.12:8333 (outbound) (/Satoshi:0.9.0/)
07:25:00 2014-11-14 [WRN] BMGR: Received block header that does notproperly connect to the chain from peer 198.255.137.114:8333 -- disconnecting
07:25:00 2014-11-14 [INF] BMGR: Lost peer 198.255.137.114:8333 (outbound)
07:25:00 2014-11-14 [INF] BMGR: Syncing to block height 329973 from peer 24.154.138.12:8333
07:25:00 2014-11-14 [INF] BMGR: Downloading headers for blocks 300653 to 319400 from peer 24.154.138.12:8333
07:25:01 2014-11-14 [INF] BMGR: New valid peer 198.255.137.114:8333 (outbound) (/Satoshi:0.9.3/)
07:25:02 2014-11-14 [WRN] BMGR: Received block header that does notproperly connect to the chain from peer 24.154.138.12:8333 -- disconnecting
07:25:02 2014-11-14 [INF] BMGR: Lost peer 24.154.138.12:8333 (outbound)
[...]
```

The last few lines repeat indefinitely.

(Notice also the typo 'notproperly'.)

### LINKED ISSUE #614: Block processing seems to block peer handling
It appears that while processing a new block, the server is unresponsive to e.g. new connections. This leads to log lines like the following:

```
00:11:51 2016-02-02 [INF] BMGR: Processed 1 block in the last 3m19.72s (2934 transactions, height 386713, 2015-12-04 20:05:00 +0000 UTC)
00:11:51 2016-02-02 [INF] BMGR: New valid peer 52.24.121.xxx:51598 (inbound) (/Satoshi:0.11.0/)
00:11:51 2016-02-02 [INF] BMGR: New valid peer 176.58.96.xxx:57129 (inbound) (/bitcore:1.1.0/)
00:11:51 2016-02-02 [INF] BMGR: Lost peer 52.24.121.xxx:51598 (inbound)
00:11:51 2016-02-02 [INF] BMGR: Lost peer 176.58.96.xxx:57129 (inbound)
```

It seems like the incoming connection likely happens during block processing, and is processed and dropped immediately as soon as the block is processed. (Note that my node still doesn't seem to be synced, which may explain why the other side disconnects immediately, but not that it is logged only after block processing.)

I can't rule out that this is only a logging issue.

### LINKED ISSUE #697: Two btcd instanced on same machine keep losing connection
I setup one daemon that was synced up and listening to 8335 and another one with `connect=127.0.0.1:8335` that started from scratch.

However, they kept losing connection:

```
00:02:56 2016-05-19 [INF] BMGR: Syncing to block height 412025 from peer localhost:8335
00:02:56 2016-05-19 [INF] BMGR: Downloading headers for blocks 1 to 11111 from peer localhost:8335
00:04:41 2016-05-19 [INF] BMGR: Lost peer localhost:8335 (outbound)
```

I found this in the debug logs and the probable cause:

```
00:56:30 2016-05-19 [DBG] PEER: Peer 127.0.0.1:8335 (outbound) appears to be stalled or misbehaving, headers timeout -- disconnecting
```

That message occurred on the new (connecting) instance.

I talked about it with @davecgh and he could not immediately identify the issue. The receiving instance does not mention anything special about the other instance, just that it received a `getheaders` message.

Here are some more possibly relevant logs:
https://gist.github.com/stevenroose/5b69ed22d8fd35d8c04c564c0f3733b7
https://gist.github.com/stevenroose/a06184820c7b44c96d9728072ae2886a
https://gist.github.com/stevenroose/7e6265c06b505b4e51733b6b15eae883

### LINKED ISSUE #776: Stall detection should only really happen for the sync peer
Right now btcd has no multipeer syncing support, so there is exactly one syncpeer that it might be syncing from at any time.

It is important to have stall detection for this sync peer.  If the peer stalls, it should be kicked so another peer can be chosen.  Failing to do so can result in your node getting stuck because the sync peer is stuck.

However, it is not nearly as important to apply this same stall detection to other peers that are not your sync peer.  These nodes can be kept connected for far longer, and this should prevent many of the issues with disconnecting peers that take too long to respond to some request.

I'm unsure if the stall detection should be completely removed for these non-sync peers, or if it should be applied with a longer timeout.  Investigation and analysis is required.

### LINKED ISSUE #1024: Bad sync peer stalls sync
I talked about this on IRC, so here is an overview.

I noticed that my node failed to catch up. After restarting, it would catch up for some time and stall again.

I noticed that when the syncing stalls, my sync peer is always this one:
```json                                                                                                                                                                                        
  {                                                                                                                                                                                                                              
    "id": 21,                                                                                                                                                                                                                    
    "addr": "46.4.167.78:46826",                                                                                                                                                                                                 
    "addrlocal": "80.67.181.176:8333",                                                                                                                                                                                           
    "services": "00000005",                                                                                                                                                                                                      
    "relaytxes": true,                                                                                                                                                                                                           
    "lastsend": 1503432722,                                                                                                                                                                                                      
    "lastrecv": 1503432722,                                                                                                                                                                                                      
    "bytessent": 29326,                                                                                                                                                                                                          
    "bytesrecv": 798121,                                                                                                                                                                                                         
    "conntime": 1503431192,                                                                                                                                                                                                      
    "timeoffset": 0,                                                                                                                                                                                                             
    "pingtime": 56181,                                                                                                                                                                                                           
    "version": 70013,                                                                                                                                                                                                            
    "subver": "/btcwire:0.5.0/btcd:0.12.0/",                                                                                                                                                                                     
    "inbound": true,                                                                                                                                                                                                             
    "startingheight": 481628,                                                                                                                                                                                                    
    "currentheight": 481628,                                                                                                                                                                                                     
    "banscore": 0,                                                                                                                                                                                                               
    "feefilter": 0,                                                                                                                                                                                                              
    "syncnode": true                                                                                                                                                                                                             
  }
```

So after removing this peer, btcd picks another sync peer and syncing resumes. Until that peer goes offline and this same inbound btcd peer is chosen as sync peer and it stalls again.

So there are two problems here:
 - When there is no sync progress, we should chose another sync peer.
 - Do we favor some peers over others to be sync peers? (Like btcd ones f.e.?) Maybe that's not a very good idea.


Just to be clear: I reproduced this several times. 
1. notice stall with btcd sync peer
2. disconnect sync peer
3. notice progress with other peer
4. notice that same btcd node reconnects inbound
5. disconnect sync peer
6. notice stall from btcd sync peer

This is some part of debug log that includes the traffic right after the btcd sync peer is picked: https://gist.github.com/stevenroose/f60df52886c2dfdb71985a29cbcd80a6

This btcd node seems to be either malicious or without bandwidth to upload. It might be a bug in btcd, but I highly doubt that. But the fact that we keep favoring him to do sync is bad anyway.

### LINKED ISSUE #1099: btcd stops syncing after losing connection from peer
I've been trying to sync up to the present day and have been unable to. btcd starts, and verifies blocks for some amount of time, then this happens:

```
2017-12-13 20:01:47.614 [INF] SYNC: Processed 2 blocks in the last 14.49s (1172 transactions, height 472205, 2017-06-20 23:56:18 -0400 EDT)
2017-12-13 20:02:00.565 [INF] SYNC: Processed 2 blocks in the last 12.95s (4074 transactions, height 472207, 2017-06-21 00:19:25 -0400 EDT)
2017-12-13 20:02:13.003 [INF] SYNC: Processed 2 blocks in the last 12.43s (4055 transactions, height 472209, 2017-06-21 00:56:11 -0400 EDT)
2017-12-13 20:02:19.661 [INF] SYNC: Lost peer 213.239.210.153:8333 (outbound)
2017-12-13 20:02:19.663 [INF] SYNC: Syncing to block height 499163 from peer 108.59.9.167:8333
2017-12-13 20:02:50.514 [INF] SYNC: New valid peer 89.163.224.195:8333 (outbound) (/Satoshi:0.14.0/)
2017-12-13 21:09:26.536 [WRN] PEER: Peer 92.255.126.23:8333 (outbound) no answer for 5m0s -- disconnecting
2017-12-13 21:09:26.536 [INF] SYNC: Lost peer 92.255.126.23:8333 (outbound)
2017-12-13 21:11:56.954 [INF] SYNC: New valid peer 52.10.150.72:8333 (outbound) (/Satoshi:0.15.0.1/)
2017-12-13 21:12:00.331 [INF] SYNC: Lost peer 52.10.150.72:8333 (outbound)
```

After a few attempts like that, it gives up and idles for days until I remember to check on it and I restart the server.

What's with that?

### LINKED ISSUE #1136: btcd sync keeps freezing
It runs for about 1 hour, then dies.  I see this because a) the cpu usage drops from 180% to 1%, and when I poll the server on https://bitnodes.earn.com the height stays the same (and the % goes down).

We have been trying to sycn the blockchain since a week.  It runs for an hour or two then stops syncing.  The process is still running.

When it stops syncing, the logs fill up with stuff like this:

2018-03-03 19:30:17.509 [INF] SYNC: New valid peer 52.54.198.224:8333 (outbound) (/Satoshi:0.16.0/)
2018-03-03 19:30:26.116 [INF] SYNC: New valid peer 62.183.116.182:22567 (inbound) (/Satoshi:0.15.0/)
2018-03-03 19:31:23.173 [INF] SYNC: Lost peer 62.183.116.182:22567 (inbound)
2018-03-03 19:32:23.587 [INF] SYNC: New valid peer 46.101.246.115:47819 (inbound) (/Snoopy:0.2.1/)
2018-03-03 19:32:23.748 [ERR] PEER: Can't read message from 46.101.246.115:47819 (inbound): read tcp4 45.33.44.212:8333->46.101.246.115:47819: read: connection reset by peer
2018-03-03 19:32:23.748 [INF] SYNC: Lost peer 46.101.246.115:47819 (inbound)
2018-03-03 19:32:26.108 [INF] SYNC: New valid peer 128.235.40.191:12835 (inbound) (/btc.cs.njit.edu:0.1/)
2018-03-03 19:32:27.421 [INF] SYNC: Lost peer 128.235.40.191:12835 (inbound)
2018-03-03 19:32:48.002 [INF] SYNC: New valid peer 18.196.84.227:49734 (inbound) (/bitcoin-seeder:0.01/)
2018-03-03 19:32:49.148 [INF] SYNC: Lost peer 18.196.84.227:49734 (inbound)

The only solution is to restart the btcd process every couple of hours, but we can only do this when we are online.  It is going to take months at this rate.

The server is a linode ubuntu 16 LTS with 4 GB ram, dual core, and 300GB secondary volume for data.

we tried disabling the listener, but this did not help

### LINKED ISSUE #1405: btcd stops processing blocks
I've run into this issue mainly on the initial sync, as blocks download one expects `processed X blocks in the last Y minutes/seconds` in the trace, but stops before reaching the end of the chain and process needs to be restarted several times throughout the initial warm-up to complete. 

I've now noticed this a few times now with a fully synch'd btcd (mainnet), even where I am already restarting it every 24 hours for lack of better monitoring. Note the btcd process itself does not fail, but rather it simply ceases processing of new blocks.

Initially I thought this was due to constrained memory/cpu resources in my environment, but have now had this occur again on a separate and more powerful piece of hardware (Ubuntu 16+ x64 systems). 

Any thoughts on troubleshooting much obliged.

### PR DESCRIPTION
**Pull request by cfromknecht**
Adds stall detection when no blocks have been received from the sync
peer for at least 3 minutes.

The change backports parts of gcash/bchd#105,
though has different behavior, such as:
 - Rotating the sync peer at tip.
 - Only disconnecting the sync peer if they're height exceeds our own.
   Since we will instead rotate the sync peer at tip, this prevents us
   from disconnecting good peers while waiting for new blocks.
 - Not resetting the progress time when blocks are submitted via rpc.

Closes #697. 
Closes #776. 
Closes #1024. 
Closes #1099. 
Closes #1136. 
Closes #1405. 
Closes #186. 
Closes #614.

### CODE REVIEW

File: netsync/manager.go [hunk 1]
```diff
@@ -406,18 +418,29 @@ func (sm *SyncManager) handleDonePeerMsg(peer *peerpkg.Peer) {
...
+// dcSyncPeer is true, this method will also disconnect the current sync peer.
+// If we are in header first mode, any header state related to prefetching is
+// also reset in preparation for the next sync peer.
+func (sm *SyncManager) updateSyncPeer(dcSyncPeer bool) {
+	log.Infof("Updating sync peer, no progress since: %v",
+		time.Since(sm.lastProgressTime))
+
+	// First, disconnect the current sync peer if requested.
+	if dcSyncPeer {
+		sm.syncPeer.Disconnect()
```
Comment (Roasbeef) [inline netsync/manager.go]: If we're entering `handleDonePeerMsg`, then the peer has already been disconnected.

File: netsync/manager.go [hunk 2]
```diff
@@ -393,6 +393,18 @@ func (sm *SyncManager) handleDonePeerMsg(peer *peerpkg.Peer) {
 
 	log.Infof("Lost peer %s", peer)
 
+	sm.clearRequestedState(state)
+
+	if peer == sm.syncPeer {
+		// Update the sync peer and disconnect our current sync peer.
+		sm.updateSyncPeer(true)
```
Comment (Roasbeef) [inline netsync/manager.go]: I think this can just be `false` since the peer has already been disconnected at this point.

File: netsync/manager.go (hunk 1 above)
Comment (cfromknecht) [reply netsync/manager.go]: the case from `handleDonePeerMsg` is now set to false, leaving this though since we still use it in the stall case.

**Comment by cfromknecht** [comment]
@Roasbeef comment addressed, ptal. can squash when ready

**Comment by cfromknecht** [comment]
@Roasbeef rebased
