### PR TITLE
peer: fix panic due to err in handleVersionMsg

### LINKED ISSUE #579: panic with peer / addrmgr
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x6876a8]

goroutine 827 [running]:
github.com/btcsuite/btcd/addrmgr.NetAddressKey(0x0, 0x0, 0x0)
        /home/dhill/.go/src/github.com/btcsuite/btcd/addrmgr/addrmanager.go:734 +0x28
main.(*serverPeer).OnVersion(0xc8200a8400, 0xc82220c840, 0xc82200da00)
        /home/dhill/.go/src/github.com/btcsuite/btcd/server.go:345 +0x3f7
main.(*serverPeer).OnVersion-fm(0xc82220c840, 0xc82200da00)
        /home/dhill/.go/src/github.com/btcsuite/btcd/server.go:1405 +0x34
github.com/btcsuite/btcd/peer.(*Peer).inHandler(0xc82220c840)
        /home/dhill/.go/src/github.com/btcsuite/btcd/peer/peer.go:1532 +0xe62
created by github.com/btcsuite/btcd/peer.(*Peer).Start
        /home/dhill/.go/src/github.com/btcsuite/btcd/peer/peer.go:2017 +0x2c9

goroutine 1 [chan receive, 7 minutes]:
main.btcdMain(0x0, 0x0, 0x0)
        /home/dhill/.go/src/github.com/btcsuite/btcd/btcd.go:133 +0xe5d
main.main()
        /home/dhill/.go/src/github.com/btcsuite/btcd/btcd.go:163 +0x184
```

### PR DESCRIPTION
**Pull request by tuxcanfly**
In case of an error during protocol negotiation in `handleVersionMsg`,
immediately break out and prevent further processing of `OnVersion`
listener which generally depends upon peer attributes like `NA` to be set
during the negotiation.

Fixes #579.

[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/580)

### CODE REVIEW

File: peer/peer.go [hunk 1]
```diff
@@ -1527,7 +1516,13 @@ out:
 		p.stallControl <- stallControlMsg{sccHandlerStart, rmsg}
 		switch msg := rmsg.(type) {
 		case *wire.MsgVersion:
-			p.handleVersionMsg(msg)
+			err := p.handleVersionMsg(msg)
+			if err != nil {
+				log.Errorf("New peer %v - error negotiating protocol: %v",
```
Comment (davecgh) [inline peer/peer.go]: Debugf

**Comment by davecgh** [comment]
Also, please name the commit message subsystem correctly:

`peer: fix panic due to err in handleVersionMsg `

Then put the `Fixes #579` in the commit description.  It typically goes as the end.

**Comment by tuxcanfly** [comment]
Thanks, updated.

**Comment by davecgh** [comment]
OK
